---
title: "テキスト前処理<br> + 形態素解析"
author: "岸山 健"
date: '`r format(Sys.time(), "%Y/%m/%d %H:%M")`'
output:
  ioslides_presentation:
      transition: faster
---

<!-- 
library ('rmarkdown'); render('report.Rmd')
fig.align: center
-->

```{r setup, include=FALSE}
# セットアップチャンク
# パッケージのロード，データ読み込みなど，Rオプション設定など
# options(width = 1000)
# dat = read.table("hoge")
# 全てのコードチャンクに適用されるオプション
# knitr::opts_chunk$set(warning=FALSE)
# knitr::opts_chunk$set(message=FALSE)
# knitr::opts_chunk$set(echo=FALSE)
knitr::opts_chunk$set(
    # echo = FALSE,
    message = FALSE,
    warning = FALSE,
    fig.align='center',
    fig.pos='H',
    dev = c("png", "svg"),
    dpi=500
)
library(DT)
```

## テキスト前処理 + 形態素解析

1. 共通接頭辞検索(徳永 2012, p.75)
    * データ構造:トライ木
    * 実装:テーブル

## 実装(テーブル) {.smaller}

```{r}
d <- read.table("dict.csv",sep='\t', header=TRUE)
d[is.na(d)] <- -1
```

```{r,echo=FALSE}
datatable(d,options = list(pageLength=9))
```

## 実装(トライ木の探索) {.smaller}

* d.tableは辞書のテーブル

```{r}
search <- function(key, d.table){
    state <- 0
    # 通ったパスをstatsに保存
    states=c(state)
    key.len <- nchar(key)
    for (i in 1:key.len){
        k_i <- substring(key, i, i)
        if( !(k_i %in% colnames(d.table)) ){
            return(states)
        }
        next_s <- as.numeric(subset(d.table, d.table$pid==state)[k_i])
        if (next_s == -1){
            break
        }else{
            state=as.numeric(next_s)
            states=c(states,state)
        }
    }
    return(states)
}
```

## 実装(トライ木の探索) {.smaller}

* d.tableは辞書のテーブル
* 全て得なくてはならない

```{r}
# たべた
key="たべものが体質にあった"
search(key, d)
key="たべたものが体質にあった"
search(key, d)
key="たべるものが体質にあった"
search(key, d)
key="たべたものが体質にあった"
search(key, d)
key="べたもたものが体質にあった"
search(key, d)
```

## あとはここまでくれば
